### ISSUE TITLE
[误杀]无法接收邮件

### ISSUE THREAD

**Issue by wuzhushu** [banbendalao/ADgk#12]
网址： iwx.mail.qq.com
场景：拦截此规则，导致QQ邮箱APP无法接收与查看邮件，放行则可以
手残....发了三个才发对

**Comment by banbendalao** [comment]
我使用安卓QQ邮箱6.1.7无法复现该问题，可以提供一下你现在使用的QQ邮箱APP版本吗

**Comment by wuzhushu** [comment]
苹果6.1.5,安卓6.1.7。两个手机都在用。都有类似的情况，不知道是不是我这边设置的问题

**Comment by wuzhushu** [comment]
不好意思，我现在也无法复现这个问题，可能是我这边的设置错误
