### ISSUE TITLE
[请求拦截] 今日校园

### ISSUE THREAD

**Issue by Leisuredpootle** [banbendalao/ADgk#15]
网站网址/app下载地址：  今日校园
出现场景：进主页后的弹窗和主页的banner
抓包后自写规则,经自测几日,无错误拦截:
/ad$app=com.wisedu.cpdaily
/v3/modelView/get/new$app=com.wisedu.cpdaily

另附上部分数据回报
||feedback.cn.ronghub.com^
/report$app=com.wisedu.cpdaily
||sensorsdata.cn^

**Comment by banbendalao** [comment]
请尽量提交包含完整url的规则如`||example.com/ad`，如有特殊情况请说明原因

**Comment by Leisuredpootle** [comment]
https://mobile.campushoy.com/v6/ad/group/HOME/ad/list?adType=FLOAT&oick=一串字符
以下为抓包内容
[1616686879432.zip](https://github.com/banbendalao/ADgk/files/6206018/1616686879432.zip)



https://mobile.campushoy.com/v3/modelView/get/new?oick=一串字符
以下为抓包内容
[1616686934890.zip](https://github.com/banbendalao/ADgk/files/6206017/1616686934890.zip)

sensorsdata.cn 为大数据统计平台

feedback.cn.ronghub.com
https://183.232.25.151/v3/report 用于其软件自身的log上传
