### ISSUE TITLE
[误拦截报告] 网易邮箱大师无法获取邮件

### ISSUE THREAD

**Issue by Star-ZER0** [banbendalao/ADgk#17]
使用主规则规则
网易邮箱大师登录IMAP QQ邮箱无法刷新获取邮件，禁用过滤器后可以刷新，初步判断误拦截，望改进！
希望dalao的过滤器越做越好！

**Comment by banbendalao** [comment]
无法复现，请检查你使用的其他规则和设置，或提供有效过滤日志

**Comment by Star-ZER0** [comment]
![Screenshot_20210411-221716_AdGuard](https://user-images.githubusercontent.com/65442169/114307811-ce22c080-9b13-11eb-9249-836732d8a68b.png)
图为仅开启ADgk过滤器的过滤日志
未开启其他过滤器及dns过滤器
ps：学生党所以很少上github

**Comment by Star-ZER0** [comment]
未开启过滤器时qq邮箱imap协议收信一切正常

**Comment by Vstory** [comment]
用户过滤器添加
`@@||iwx.mail.qq.com^`
QQ邮箱就可以正常了。
