### ISSUE TITLE
[误杀]https://www.pianku.li/片库网影片封面图片被干掉了

### ISSUE THREAD

**Issue by qpzr** [banbendalao/ADgk#19]
23:14:38
2021/4/19
pic.iask.cn
类型: A, 无加密DNS
响应细节
状态
已拦截
耗时
2 毫秒
响应代码
NOERROR
规则
||iask.cn^

响应
A: 0.0.0.0 (ttl=600)

**Comment by banbendalao** [comment]
ADgk内未包含`||iask.cn^`规则

**Comment by qpzr** [comment]
> ADgk内未包含`||iask.cn^`规则

感谢解答，找到问题所在了，是anti-AD规则抓取工具的问题
