### ISSUE TITLE
在via中百度百科和百度知道都被拦截

### ISSUE THREAD

**Issue by ccjjxx99** [banbendalao/ADgk#2]
在via自带的广告过滤中使用时，百度百科和百度知道都被拦截，也许这是via的bug吗？

**Comment by banbendalao** [comment]
> 在via自带的广告过滤中使用时，百度百科和百度知道都被拦截，也许这是via的bug吗？

每个软件对规则的处理逻辑都不太一样，很难保证所有软件都能达到同样的效果
