### ISSUE TITLE
新增拦截[请求拦截]

### ISSUE THREAD

**Issue by mcnk328** [banbendalao/ADgk#20]
网站网址/app下载地址：  ||api.blibili.com/x/pd-proxy/tracker*
出现场景：play版bilibili客户端

**Comment by banbendalao** [comment]
请简单描述该规则的用途

**Comment by mcnk328** [comment]
> 请简单描述该规则的用途

我自己测试了10多次，清空后台打开b站，在不点击视频观看的情况下，则不会访问该链接，点击任意视频观看后则会访问一次链接，也只访问一次，后续观看其它视频也不再访问该链接，除非清空后台重新打开才会。目前我无法判定该链接是否有涉及跟踪用户隐私的行为，所以没法下定论，但是我这边自定义规则里边已经屏蔽了，也不会影响到使用。
