### ISSUE TITLE
Ran PyFunceble on adgk.txt

### ISSUE THREAD

**Issue by sr093906** [banbendalao/ADgk#26]
PyFunceble -f _raw file on system_ -c --dns 1.2.4.8 8.8.8.8 (The files are attached to the end. You can verify the results yourself.)

The project decides whether a domain is active by three dimensions, HTTP status code, WHOIS record and DNS Lookup.

More info:
https://pyfunceble.readthedocs.io/en/latest/usage/index.html#from-a-terminal

These domains and IPs are marked as INACTIVE of the 1st party rules:

0551zgz.com  
0o.868iy.cn  
1.201980.com  
1.32xp.com  
1.codezh.com  
1.dwx365.com  
1.hnyouneng.com  
1.i1766.com  
1.jeasyui.net  
1.qt86.com  
1.rr95.com  
1.win7china.com  
1.wosoni.com  
1.xiaopin5.com  
1.xuexi.la  
1.zou114.com  
1.zw3e.com  
103.49.209.27  
104.195.62.12  
104.233.203.164  
104.237.67.78  
106.187.95.251  
11.golang8.com  
112.74.95.46  
114.95.102.77  
115.238.246.181  
116.55.227.242  
119.4.249.166  
122.227.254.195  
122.228.236.165  
123.59.150.56  
139.159.32.82  
156.247.120.15  
156.247.120.31  
162.209.213.66  
194.36.101.178  
1x26q3.cn  
2.heiyange.com  
2.rengshu.com  
2016.bkill.net  
21.cizhibaogao.org  
211.103.159.32  
211.91.124.16  
212.64.34.17  
218.25.246.118  
219.234.83.60  
27pan.2wk.com  
3.chuanyi5.com  
3.guidaye.com  
3t7p.cn  
42.51.8.24  
45.126.123.80  
45.34.240.72  
47.90.50.177  
4ekx.cn  
4z5o27.cn  
58.215.179.159  
5jcom.com.cn  
5x0f.cn  
5y69n.cn  
66.zx1234.com  
6e5.3665de.com  
6oug.cn  
7011.stia.cn  
77xtv.com  
7891655.cn  
7mad.7m.cn  
86file.megajoy.com  
8byu.cn  
9d7in.cn  
a.779.net  
a.armystar.com  
a.baomihua.com  
a.duanmeiwen.com  
a.duduji.com  
a.fwsir.com  
a.icdol.com  
a.jing55.com  
a.kejixun.com  
a.market.xiaomi.com  
a.psxxw.cn  
a.qsjiajiao.com  
a.thn21.com  
a.xmdly.com  
a.xxdy8.cn  
a.yl-taikang.com  
a.yuzhainan.com  
a1.7down.com  
a1.aluntan.com  
a1.gexing.me  
a1.qqjay.com  
a1.vdolady.com  
a1.yuuedu.com  
a2f52ef3b52.top  
a6s.hn985.com  
aa.xiangxiangmf.com  
aa1.ifeng.com  
aaalian.com  
ab.sspsky.com  
abcj.dooccn.com  
ac1.faxingchina.com  
acm.dzwww.com  
acsystem.wasu.cn  
ad.ixigua.com  
ad.kuaishou.com  
ad.wx.com  
ad1.p5w.net  
ad1.xiaomi.com  
add.mmyuer.com  
adhome.1fangchan.com  
adn.baidu.com  
adnet.sohu.com  
adp.cnki.net  
adsclick.yx.js.cn  
adserviceretry.kglink.cn  
afp.chinanews.com  
afp.wasu.cn  
afpcreative.wasu.cn  
aima.shouhome.com  
ajkdg3.xyz  
ali2d.xyz  
ams.fx678.com  
analytics.126.net  
ao.r7f.ifeng.com  
api.game.letvstore.com  
app.codefund.io  
appsrv1.madserving.cn  
as.g4.ifeng.com  
as.g5s.ifeng.com  
atm.youku.com  
aty.sohu.com  
b.kouke5.com  
b.whrdch.com  
b0lc.cn  
b1.91jucai.com  
b7sw62.pingshu8.xyz  
baidu.cmxsw.com  
baidujs.cnys.com  
baiduwapjs1.chinaiiss.com  
bbs2.chinaz.com  
bd.ershenghuo.com  
bd.m.biqugeso.com  
bd.scw98.com  
bd1.jinbaozy.com  
bd1.ningboseo0574.com  
bd1.nxing.cn  
bd1.wowoqq.com  
bdad.gaotie.net  
bdasd.chinabig.com.cn  
bdasd.wmxa.cn  
bdcode.35d1.com  
bddm.58news.org  
bdjb.gai001.com  
bdjj.makepolo.net  
bdjs.faxingzhan.com  
bdjs.ylq.com  
bdu1.eol.cn  
biochempop.com  
biz.weibo.com  
bpdffh.cn  
bs.da.hunantv.com  
by.7avz.com  
by.dm5.com  
c.mnjkw.cn  
c.xiaozhuyoupu.com  
c1.4qx.net  
c6.friok.com  
caicaicai.121yy.com  
cdn.hivps.xyz  
cdn.m.okdd.net  
ceyiuy.com  
cgm.shicimingju.com  
cjie.baidu.com  
cms.fx678.com  
code.comuce.com  
code.kaixinjiehun.com  
code.qihoo.com  
cp81.ott.cibntv.net  
cpc.xioo.cn  
cpm.cm.kankan.com  
cpm.cm.sandai.net  
cpms.cc  
css.juqingba.cn  
d.2945.com  
d.ab126.com  
d.feih.com.cn  
d.gz2010.cn  
d.kglink.cn  
d.wiyun.com  
d.xaoyo.com  
d.ynjk120.com  
d1.zhuangxiu6.com  
da.mgtv.com  
dai.siyuetian.net  
daima.23yy.com  
daima.huoche.net  
daima.ijq.tv  
daima.niubb.net  
das.biquge3.com  
data.mgtv.com  
data.pplive.com  
data.waptime.cn  
dds.sogua.com  
deliver.ifeng.com  
dev.dc.letv.com  
df666.pzhttaax.cn  
df888.eastday.com  
dimg1.sz.net.cn  
dkg.ifeng.com  
dm.51okc.com  
dm.66qw.net  
dm.66wenshen.com  
dm.huochepiao.com  
dm.pw0.cn  
dm.riji.cn  
dm.wenshenxiu.com  
dm.xjfat1.com  
dm.zhiyuanteam.com  
dmr.cnhoney.com  
dmswhw.cn  
dows.yuyudl.com  
drmcmm.baidu.com  
duiwai.baidu.com  
e.yycqc.com  
ecuwa.cn  
ee.shixunwang.net  
eeo.5du5.com  
epukult.cn  
f.520tingshu.com  
feedback.qy.net  
ff.guidaye.com  
float.kankan.com  
fp.jj59.com  
fpb.kuhou.com  
frjxdv.cn  
fun.ynet.com  
future888.net  
g.3lian.com  
g8f.ifeng.com  
gamex.mobile.youku.com  
gb.it1352.com  
gd.mm2004.com  
gg1.mengchongzu.com  
gm682.com  
goto.www.iciba.com  
guess.h.qhimg.com  
ha.zixuekaoshi.net  
haixiaqy.com  
hao.360hyzj.com  
hao123.sina.yxcjqy.com  
hdc.maxli.cn  
hermes.airad.com  
hi.xiunm.com  
hi2.totolook.com  
hiad.vmall.com  
home.wangmeng.com  
houyi.baofeng.net  
hp.smiler-ad.com  
hrcmzp.cn  
ht.ruanjiancms.com  
hu.xbhy.com  
huashengtai.net  
hz.shouyoutv.com  
i.syasn.com  
i05h.cn  
iads.xinmin.cn  
images.ccqxqc.com  
img.263y.com  
img.meipic.net  
img.xuenb.com  
img.yqgytx.com  
img2.126.net  
img2.pengfu.net  
int.w3tong.com  
ioahdio.com  
iouqxvr.cn  
ip.hivps.xyz  
ipic.staticsdo.com  
iwanad.baidu.com  
j.7avz.com  
j.ajaxxy.net  
j.avz4.com  
j.chuanxianwanguan.com  
j.geluck.net  
j.imdb.cn  
j.taokeweizhan.com  
jiaoben.eastday.com  
js.45bubu.com  
js.bju888.com  
js.itaiju.com  
js.jianbihuadq.com  
js.kt250.com  
js1.bju888.com  
jssumei.cn  
jvyigg.biquge.lu  
jwhfn.cn  
jxad.jx163.com  
kfuih.cn  
kkds.xntk.net  
klvvo.xhzlovehyx.cn  
ku.biquge.info  
l.ftx.fancyapi.com  
la61d.cn  
lang.t7114.com  
ld.kuaigames.com  
links.panr.com  
linyao.dxsdb.com  
ll.gxsky.com  
lm1.wzpcw.com  
load.jsecoin.com  
log.aliyuncs.com  
logger.baofeng.com  
ltsnpw.cn  
lv.myapks.com  
lv55p.cn  
lyz.radio366.com  
m.5s7uo.cn  
m.beidouxin.com   
m.cpgzh.com  
m.h0x.cn  
m.uocb.cn  
m.xs222.com  
m2.lelemh.com  
maxfull.info  
mdt.qq.com  
minemytraffic.com  
miner.pr0gramm.com  
miniye.xjts.cn  
mkaqh.cn  
mm.awrsx.cn  
mobad.ijinshan.com  
moyangao.com  
mp.miaomiaojia.cc  
msg.m.letv.com  
msg.mobile.kglink.cn  
mx.biquge.info  
my.gz2010.cn  
nickarini.com  
njs.myhx120.com  
nubao.lsdys.cn  
o.jy135.com  
oiwjcsh001.top  
oiwjcsh010.top  
oiwjcsh012.top  
olc0.cn  
oohxa.xyz  
p.vf5c.com  
p.yjunzi.com  
p4p.sina.com.cn  
pan.keyunzhan.com  
pb.okk123.com  
pb.shuxigua.com  
photo.dstrchina.cn  
photo.paiji188.cn  
pic.fengniao.com  
pingbi.diudou.com  
pkk1.zuimeiniwo.com  
pop.91mangrandi.com  
pp.wayqq.com  
ppurifier.game.xiaomi.com  
pzvlnh.cn  
qd.snwx.com  
qd.x4399.com  
qdiut.com  
qihmob.com  
qneit.com  
qr.youlu.com  
qt.biqugezw.com  
qzdfc.com  
rad.msn.com  
rcynoe.cn  
rdxhrd.com  
resource.baomihua.com  
rqd.qq.com  
rxxdq.cn  
s.cq20.cn  
sayhi.360.cn  
sbbd1.qulishi.com  
script.vccoo.com  
sgcmoeu.cn  
shicao.icantv.cn  
shili.downxia.com  
show.sogua.com  
show.xiazai16.com  
sl.video.xycdn.n0808.com  
smf82.cn  
snyu.sdo.com  
spahelani.com  
spcode.baidu.com  
sphwq.net  
src.ting76789.cn  
ss.shicimingju.com  
static.52zzyx.com  
static.jiaquyi.com  
static8.pmadx.com  
t.douyaobuy.com  
tg.52digua.com  
tiaoweiyou.cn  
tiexu.biquge.info  
tip.biquge.info  
tjtiebz.cn  
tlgg.itruni.com  
tt.biquge.la  
tt.douyaobuy.com  
tt123.eastday.com  
tuisong.baidu.com  
tv.ytbctyy.com  
twin13a131.sandai.net  
u1.shuaiku.com  
union1.cnbetacdn.com  
unionch.qyule.com  
uniondm.cz88.net  
up.hiao.com  
uzyid.cn  
v1.taksh.cn  
variety.tc.qq.com  
vf5yb4.cn  
vruuzgf.cn  
vv1.pyhfxdm.cn  
vvv.ieduw.com  
w1.diaoyou.com  
w1.wayqq.com  
wcail.com  
wda.ydt.com.cn  
wew.dushiwenxue.net  
wjdjcjcm444.cn  
wqsph.net  
ws.wenshenxiu.com  
wsoue.com  
wu.biquge.info  
wuliao.chzsport.cn  
wuliao.juqingba.cn  
www.91860.com  
www.xiukeshop.com  
wxs.qq.com  
x.wvez.cn  
x0lh.cn  
xc.gouchezj.com  
xc.mydrivers.com  
xcf-bd-js.chuimg.com  
xdywlw.cn  
xgbercp.cn  
xiaopangtao.com  
xindelin.cn  
xinhuawei.cxd88.com  
xlmc.sandai.net  
xlmc.sec.miui.com  
xpowerad88js.com  
xyssp.com  
ybaiu.com  
ydeprint.com  
yh303030.com  
yizhijin.cn  
ym.2liang.com  
youhm.cn  
ywqum.cn  
ywxtmox.cn  
yx1.managershare.com  
yyo.5du5.com  
zfanc.com  
zg.mmyuer.com  
zhgg.dre8.com  
zhn.cynouk.cn  
zhonghuayidao2.com  
zyadvertstatic.beizengtech.com  

These domains and IPS are marked as INACTIVE of the 3rd block rules:

115.29.148.61
265union.com
adm.cnzz.net
aifei.info
aoodoo.weiphone.com
chinasms-b2b.com
elsad.tw
game.466.com
lianjie.phpwind.com
lm.35.com
mengheng.net
news.tagtoo.co
oa-panther.data.aliyun.com
symac.cn
u.ipxk.com
u.xmshqh.com
uxsurvey.baidu.com
vtale.org
waihui518.com

the raw files

[1st.txt](https://github.com/banbendalao/ADgk/files/6631377/1st.txt)
[3rd.txt](https://github.com/banbendalao/ADgk/files/6631378/3rd.txt)

**Comment by banbendalao** [comment]
I'm glad you made suggestions for this project. HTTP status codes and DNS queries are not of reference value. There are many advertisements that do not use http 80 443 to obtain data, and the main domain name is probably not bound to the IP. Only whois is suitable as a basis for domain name invalidation

**Comment by sr093906** [comment]
Glad you replied. The script will not mark a domain as inactive only because of one factor, i.e. only http code, DNS lookup or whois record. 

You could view the developer's response here.
https://github.com/StevenBlack/hosts/pull/1676#issuecomment-854257349

**Comment by sr093906** [comment]
If you had run the test, you should noticed many domains replied with non-200 http code like 404, 301 are still considered as active.

**Comment by sr093906** [comment]
Updated the lists of inactive domains and IPs to remove false positives
