### ISSUE TITLE
[误拦截] 影响视频加载

### ISSUE THREAD

**Issue by Vstory** [banbendalao/ADgk#31]
||pstatp.com/obj^

![Screenshot_2021-09-20-18-32-52-083_com adguard android](https://user-images.githubusercontent.com/20795557/133988983-b842e824-4653-4ad6-a32c-c9276b5b7720.jpg)

该规则影响视频加载
视频地址：
https://sf1-ttcdn-tos.pstatp.com/obj/tos-cn-v-0004/764704cfb3cc4541b82a91997428c6a0

**Comment by JeamMax** [comment]
注意，上面的链接是18+

**Comment by Vstory** [comment]
> 注意，上面的链接是18+

这个过滤规则组并不是成人过滤。
