### ISSUE TITLE
能否更新easylistchina部分的规则

### ISSUE THREAD

**Issue by MkQtS** [banbendalao/ADgk#41]
ADgk中的许多规则来自很久以前的easylistchina，easylistchina更新了很多内容，也移除了很多过时的、不合理的规则。

另外提个建议，可以将自定义规则与easylistchina分开，通过GitHub Actions定期合并二者作为新的ADgk，提升拦截效果。

**Comment by banbendalao** [comment]
感谢你的建议，之前有考虑过分离规则但是一直没有执行，计划在近期拆分adgk规则
