### ISSUE TITLE
[请求拦截]

### ISSUE THREAD

**Issue by Lion-hk** [banbendalao/ADgk#60]
网站网址/app下载地址：  [[abcd.com](https://vidhub.cc/vodplay/148543-5-13.html)]
出现场景：HTML5播放器下边位置的广告
误杀规则：yximgs.com^阻止了视频播放，已发现下边两个路径
@@||ali-ad.a.yximgs.com/bs2/courseHead/$domain=vidhub.cc
@@||bd.a.yximgs.com/udata/music/$domain=vidhub.cc
截图演示：。

请教一下HTML5播放器下边位置的广告，不是过滤图片链接的话
这句`<div class="module" style="position: relative!important">`怎么编写ADG规则
不能##.module，因为下边的视频图片也是module

**Comment by banbendalao** [comment]
> 这句`<div class="module" style="position: relative!important">`怎么编写ADG规则

https://github.com/banbendalao/ADgk/blob/4584d0f450dba78e70cc0f232697bde37467bc80/ADgk.txt#L6
