### ISSUE TITLE
请教如何编写这个规则

### ISSUE THREAD

**Issue by Lion-hk** [banbendalao/ADgk#64]
请问，网站变黑白色，如果拦截，ADGuard代码如何编写？
这段`<style>html {filter: progid:DXImageTransform.Microsoft.BasicImage(grayscale=1);-webkit-filter: grayscale(100%);}</style>`
![1324adbe929675c3464ecab3f20d916](https://user-images.githubusercontent.com/117522220/204997204-2b0d0fd5-fbe1-45b1-b39d-ee2811e9d4d5.png)

**Comment by Lion-hk** [comment]
好像adg不是有可以个可以替换代码的规则方式吗？如何写的。谢谢大佬的规则TXT

**Comment by Lion-hk** [comment]
例子链接：[例子](https://www.x6g.com/)

**Comment by banbendalao** [comment]
`x6g.com$$style[tag-content="grayscale(100%)"]`
