### ISSUE TITLE
||comp.360os.com^[请求拦截]

### ISSUE THREAD

**Issue by 964215963** [banbendalao/ADgk#65]
网站网址/app下载地址：https://www.pocketuni.net/appDownload.html
出现场景：打开APP之后
![图片](https://user-images.githubusercontent.com/102475890/205216209-f6d6dcbb-0cb5-4be5-a0e6-7b089d413442.png)

截图演示：
![图片](https://user-images.githubusercontent.com/102475890/205215651-14e6aea5-a838-416b-8010-0023b20be494.png)

**Comment by Lion-hk** [comment]
能确定[comp.360os.com](https://comp.360os.com/)^全是广告子域名吗

**Comment by 964215963** [comment]
> 能确定[comp.360os.com](https://comp.360os.com/)^全是广告子域名吗

其他地方没见过，至少在这个APP上是这样的
